language: ruby
rvm:
- 2.1.2
script:
- bundle exec rake
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database test;' -U postgres
- RAILS_ENV=test bundle exec rake db:schema:load
- sudo apt-get install sudo apt-get install libusb-1.0.0
-
deploy:
  provider: heroku
  api_key:
    secure: JSezXvZ5GyQcEIaJCuPFf99YBKxZSrVNTAY9SWH2gV3yS5fZoX0Ai0pAmV2Txoyw6aj1JQEIn8kxOLchB74yYtB5xsRen2O6prU2UbODx7iZv3BiYTcjpphEcjrMc1jXmagyhTq6WH7YYZRnEJBMhP6g1q8U7D++2Cg8gW1+DMs=
  app: empirical-grammar-staging
  on:
    repo: empirical-org/quill
  run: "rake db:migrate"
addons:
  postgresql: "9.3"
