language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - client/node_modules
rvm:
  - 2.3.1
script:
  - npm run test
  - bundle exec teaspoon
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - npm install  # Make use of 'postinstall' to run 'cd ./client npm install'
  - npm run build:dev:client
  - npm run build:dev:server
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 284c330b001fc405fe9b1c8a013ebaed90e6f81b0318b2e3d0df66559dd0eb3e
env:
  FOG_DIRECTORY=empirical-core-travis-test
  PROGRESS_REPORT_FOG_DIRECTORY=empirical-progress-report-travis-test
