language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
