default:
  open_positions:
    - category: 'Product'
      title: 'Software Engineer'
      angelco_url: '581557-software-engineer-rails-react-python'

    - category: 'Product'
      title: 'Senior Software Engineer'
      angelco_url: '587292-senior-software-engineer-rails-react-python'
