default:
  open_positions:
    - category: 'Product'
      title: 'Software Engineer'
      url: 'https://angel.co/company/quill-org/jobs/581557-software-engineer-rails-react-python'

    - category: 'Product'
      title: 'Senior Software Engineer'
      url: 'https://angel.co/company/quill-org/jobs/587292-senior-software-engineer-rails-react-python'

    - category: 'Operations'
      title: 'Chief of Staff'
      url: 'https://www.linkedin.com/jobs/view/2188732565/'
