default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development_env: &development_env
  adapter: postgresql
  encoding: unicode
  database: emp_gr_development
  host:     localhost
  port: 5432

test_env: &test_env
  <<: *development_env
  database: emp_gr_test

leader_db_env: &leader_db_env
  database: <%= ENV['LEADER_DB_NAME'] %>
  user: <%= ENV['LEADER_DB_USERNAME'] %>
  password: <%= ENV['LEADER_DB_PASSWORD'] %>
  host: <%= ENV['LEADER_DB_HOSTNAME'] %>
  port: <%= ENV['LEADER_DB_PORT'] %>

follower_db_env: &follower_db_env
  database: <%= ENV['FOLLOWER_DB_NAME'] %>
  user: <%= ENV['FOLLOWER_DB_USERNAME'] %>
  password: <%= ENV['FOLLOWER_DB_PASSWORD'] %>
  host: <%= ENV['FOLLOWER_DB_HOSTNAME'] %>
  port: <%= ENV['FOLLOWER_DB_PORT'] %>

development: &development
  <<: *default
  adapter: postgresql_makara
  makara:
    id: postgres_development_db
    disable_blacklist: true
    sticky: true
    master_ttl: 60
    connections:
      - role: master
        name: leader
        <<: *development_env
      - role: slave
        name: replica
        <<: *development_env

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  adapter: postgresql_makara
  makara:
    id: postgres_development_db
    disable_blacklist: true
    sticky: true
    master_ttl: 60
    connections:
      - role: master
        name: leader
        <<: *test_env
      - role: slave
        name: replica
        <<: *test_env

staging: &staging
  <<: *default
  adapter: postgresql_makara
  makara:
    id: postgres_staging_db
    disable_blacklist: true
    sticky: true
    master_ttl: 60
    connections:
      - role: master
        name: leader
        <<: *leader_db_env
      - role: slave
        name: replica
        <<: *follower_db_env

sprint:
  <<: *staging

production:
  <<: *default
  adapter: postgresql_makara
  makara:
    id: postgres_production_db
    disable_blacklist: true
    sticky: true
    master_ttl: 60
    connections:
      - role: master
        name: leader
        <<: *leader_db_env
      - role: slave
        name: dummy_replica
        weight: <%= 100 - ENV['MAKARA_REPLICA_READ_PERCENTAGE'].to_i %>
        <<: *leader_db_env
      - role: slave
        name: replica
        weight: <%= ENV['MAKARA_REPLICA_READ_PERCENTAGE'].to_i %>
        <<: *follower_db_env
