---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
staging:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:queues:
  - critical
  - default
  - low
