version: 2
jobs:
  build:
    working_directory: ~/Empirical-Core
    docker:
      - image: ruby:2.5.1
        environment:
          PG_DB: quill_test_db
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:10.5-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: quill_test_db
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "services/QuillLMS/Gemfile.lock" }}
            - bundle-cache-
          paths:
            - services/QuillLMS/vendor/bundle
      - run:
          name: Bundle Install if cache isn't present.
          command: |
            cd services/QuillLMS
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: bundle-cache-{{ checksum "services/QuillLMS/Gemfile.lock" }}
          paths:
            - services/QuillLMS/vendor/bundle
      - run:
          name: Install postgres dependencies
          command: |
            apt-get update
            apt-cache search postgres
            apt install -y postgresql-client
      - run:
          name: Copy Config files
          command: |
            cd services/QuillLMS
            cp .env-sample .env
            cp config/database.yml.circle config/database.yml
      - run:
          name: Set up DB
          command: |
            cd services/QuillLMS
            bundle exec rake db:structure:load
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/quill_test_db"
      # - run:
      #     name: Run tests
      #     command: |
      #       cd services/QuillLMS
      #       bundle exec rake spec
      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_8.11.3 | bash -
            apt-get install -y nodejs npm
      - restore_cache:
          key: npm-cache-v1-{{ checksum "services/QuillLMS/package-lock.json" }}
          paths:
            - /services/QuillLMS/.npm
      - run:
          name: Install NPM dependencies
          command: |
            cd services/QuillLMS
            npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "services/QuillLMS/package-lock.json" }}
          paths:
            - /services/QuillLMS/.npm
      - run:
          name: Run LMS Tests
          command: |
            cd services/QuillLMS
            npm test
