version: 2
jobs:
  lms_rails_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: ruby:2.5.1
        environment:
          PG_DB: quill_test_db
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:10.5-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: quill_test_db
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "services/QuillLMS/Gemfile.lock" }}
            - bundle-cache-
          paths:
            - services/QuillLMS/vendor/bundle
      - run:
          name: Bundle Install if cache isn't present.
          command: |
            cd services/QuillLMS
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: bundle-cache-{{ checksum "services/QuillLMS/Gemfile.lock" }}
          paths:
            - services/QuillLMS/vendor/bundle
      - run:
          name: Install postgres dependencies
          command: |
            apt-get update
            apt-cache search postgres
            apt install -y postgresql-client
      - run:
          name: Copy Config files
          command: |
            cd services/QuillLMS
            cp .env-sample .env
            cp config/database.yml.circle config/database.yml
      - run:
          name: Set up DB
          command: |
            cd services/QuillLMS
            bundle exec rake db:structure:load
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/quill_test_db"
      - run:
          name: Run tests
          command: |
            cd services/QuillLMS
            bundle exec rake spec
  lms_node_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "services/QuillLMS/package-lock.json" }}
          paths:
            - /services/QuillLMS/.npm
      - run:
          name: Install NPM dependencies
          command: |
            cd services/QuillLMS
            npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "services/QuillLMS/package-lock.json" }}
          paths:
            - /services/QuillLMS/.npm
      - run:
          name: Run LMS Frontend Tests
          command: |
            cd services/QuillLMS/client
            FORCE_COLOR=true npm run jest --colors
  cms_rails_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: ruby:2.3.1
        environment:
          PG_DB: quill_cms_test_db
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:10.5-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: quill_cms_test_db
          POSTGRES_PASSWORD: ""
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
        environment:
          - xpack.security.enabled: false
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-cms{{ checksum "services/QuillCMS/Gemfile.lock" }}
            - bundle-cache-cms
          paths:
            - services/QuillCMS/vendor/bundle
      - run:
          name: Bundle Install if cache isn't present.
          command: |
            cd services/QuillCMS
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: bundle-cache-cms{{ checksum "services/QuillCMS/Gemfile.lock" }}
          paths:
            - services/QuillCMS/vendor/bundle
      - run:
          name: Copy Config files
          command: |
            cd services/QuillCMS
            cp config/database.yml.circle config/database.yml
      - run:
          name: Set up DB
          command: |
            cd services/QuillCMS
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/quill_cms_test_db"
      - run:
          name: Run CMS tests
          command: |
            cd services/QuillCMS
            bundle exec rake spec
  connect_node_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: circleci/node:7.7.4
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-connect-v1-{{ checksum "services/QuillConnect/package-lock.json" }}
          paths:
            - /services/QuillConnect/.npm
      - run:
          name: Install NPM dependencies
          command: |
            cd services/QuillConnect
            npm install
      - save_cache:
          key: npm-cache-connect-v1-{{ checksum "services/QuillConnect/package-lock.json" }}
          paths:
            - /services/QuillConnect/.npm
      - run:
          name: Run QuillConnect Tests
          command: |
            cd services/QuillConnect
            FORCE_COLOR=true npm run jest --colors
  lessons_node_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-lessons-v1-{{ checksum "services/QuillLessons/package-lock.json" }}
          paths:
            - /services/QuillLessons/.npm
      - run:
          name: Install NPM dependencies
          command: |
            cd services/QuillLessons
            npm install
      - save_cache:
          key: npm-cache-lessons-v1-{{ checksum "services/QuillLessons/package-lock.json" }}
          paths:
            - /services/QuillLessons/.npm
      - run:
          name: Run QuillLessons Tests
          command: |
            cd services/QuillLessons
            FORCE_COLOR=true npm run jest --colors
  grammar_node_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-grammar-v1-{{ checksum "services/QuillGrammar/package-lock.json" }}
          paths:
            - /services/QuillGrammar/.npm
      - run:
          name: Install NPM dependencies
          command: |
            cd services/QuillGrammar
            npm install
      - save_cache:
          key: npm-cache-grammar-v1-{{ checksum "services/QuillGrammar/package-lock.json" }}
          paths:
            - /services/QuillGrammar/.npm
      - run:
          name: Run QuillGrammar Tests
          command: |
            cd services/QuillGrammar
            FORCE_COLOR=true npm run test --colors
  diagnostic_node_build:
    working_directory: ~/Empirical-Core
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-diagnostic-v1-{{ checksum "services/QuillDiagnostic/package-lock.json" }}
          paths:
            - /services/QuillDiagnostic/.npm
      - run:
          name: Install NPM dependencies
          command: |
            cd services/QuillDiagnostic
            npm install
      - save_cache:
          key: npm-cache-diagnostic-v1-{{ checksum "services/QuillDiagnostic/package-lock.json" }}
          paths:
            - /services/QuillDiagnostic/.npm
      - run:
          name: Run QuillDiagnostic Tests
          command: |
            cd services/QuillDiagnostic
            FORCE_COLOR=true npm run test --colors
workflows:
  version: 2
  build-test:
    jobs:
      # - lms_rails_build
      # - lms_node_build
      # - cms_rails_build
      # - connect_node_build
      # - lessons_node_build
      # - grammar_node_build
      - diagnostic_node_build
