version: 2
jobs:
  build:
    working_directory: ~/Empirical-Core
    docker:
      - image: ruby:2.5.1
        environment:
          PG_DB: quill_test_db
          PG_USER: quill_test_user
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:10.5-alpine
        environment:
          POSTGRES_USER: quill_test_user
          POSTGRES_DB: quill_test_db
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: |
            cd services/QuillLMS
            bundle install
      - run:
          name: Install postgres dependencies
          command: |
            apt-get update
            apt install -y postgresql-client
      - run:
          name: Copy Config files
          command: |
            cd services/QuillLMS
            cp .env-sample .env
            cp config/database.yml.circle config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: |
            cd services/QuillLMS
            bundle exec rake db:structure:load
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/quill_test_db"
      - run:
          name: Run tests
          command: |
            cd services/QuillLMS
            bundle exec rake spec