version: 2
jobs:
  build:
    working_directory: ~/Empirical-Core
    docker:
      - image: ruby:2.5.1
        environment:
          PG_HOST: localhost
          PG_USER: root
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:10.5-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: emp_gr_test
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: |
            cd services/QuillLMS
            bundle install
      - run:
          name: Install postgres dependencies
          command: apt install -y postgresql-client
      - run:
          name: Copy Config files
          command: |
            cd services/QuillLMS/config
            cp database.yml.example database.yml
      - run:
          name: Set up DB
          command: |
            cd services/QuillLMS
            bundle exec rake db:create
            bundle exec rake db:structure:load
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/emp_gr_test"
      - run:
          name: Run tests
          command: |
            cd services/QuillLMS
            bundle exec rake spec