inherit_from: .rubocop_todo.yml

Style/ZeroLengthPredicate:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/IndentAssignment:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingBlankLines:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicatedKey:
  Enabled: true

Lint/InterpolationCheck:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/SafeNavigationChain:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true
  Exclude:
    - 'QuillLMS/app/models/concerns/teacher.rb'
    - 'QuillLMS/app/models/subscription.rb'
    - 'QuillLMS/app/controllers/api/v1/focus_points_controller.rb'
    - 'QuillLMS/app/controllers/api/v1/incorrect_sequences_controller.rb'
    - 'QuillLMS/app/controllers/api/v1/questions_controller.rb'
    - 'QuillLMS/lib/tasks/firebase.rake'

Naming/AsciiIdentifiers:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true
  Exclude:
    - 'QuillLMS/config/initializers/rack-attack.rb'

Naming/MethodName:
  Enabled: true
  Exclude:
    - 'QuillLMS/app/serializers/lesson_planner/unit_serializer.rb'

Naming/VariableNumber:
  Enabled: true

Naming/VariableName:
  Enabled: true
  Exclude:
    - 'QuillLMS/lib/tasks/firebase.rake'

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/InverseMethods:
  Enabled: true

Style/MixinGrouping:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
  Enabled: true

Style/Strip:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/RedundantCapitalW:
  Exclude:
   - 'QuillLMS/config/initializers/sentry.rb'
  Enabled: true

Style/RedundantSort:
  Exclude:
   - 'QuillComprehension/app/models/question.rb'
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Layout/ClosingHeredocIndentation:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/IndentHeredoc:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  Enabled: true

Lint/DuplicateMethods:
  Exclude:
    - 'QuillLMS/app/models/concerns/teacher.rb'
    - 'QuillLMS/app/services/create_lessons_token.rb'
    - 'QuillLMS/app/controllers/api/v1/incorrect_sequences_controller.rb'

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/SendWithMixinArgument:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/For:
  Enabled: true

Style/IdenticalConditionalBranches:
  Exclude:
    - 'QuillLMS/app/controllers/sessions_controller.rb'

Style/IfInsideElse:
  Enabled: true
  Exclude:
    - 'QuillLMS/app/controllers/profiles_controller.rb'
    - 'QuillLMS/app/models/concerns/public_progress_reports.rb'

Style/NonNilCheck:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/Not:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RescueModifier:
  Exclude:
    - 'QuillLMS/db/migrate/20140916143956_make_username_downcase.rb'

Style/StderrPuts:
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - 'QuillLMS/spec/models/activity_session_spec.rb'
    - 'QuillLMS/spec/models/user_spec.rb'
    - 'QuillLMS/spec/controllers/pages_controller_spec.rb'

Lint/UriEscapeUnescape:
  Enabled: true

Style/CommentedKeyword:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Layout/AlignArray:
  Enabled: true
  Exclude:
    - 'QuillCMS/spec/workers/rematch_response_worker_spec.rb'
    - 'QuillLMS/script/map_concepts_to_activities_across_apps.rb'

Style/NilComparison:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true
