# Setting the variables, statement_timeone based on this
# https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts#postgresql
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || "180s" %>

development_env: &development_env
  database: quill_cms_development
  host: localhost
  port: 5433
  user: root
  password: password

test_env: &test_env
  <<: *development_env
  database: quill_cms_test

# While we don't actually connect to any follower DBs, they
# do exist within our infrastructure, so naming conventions
# here are intended to simplify later decision to use followers
# as well as disambiguate similarly-named ENV variables.
elastic_beanstalk_leader_env: &elastic_beanstalk_leader_env
  database: <%= ENV['RDS_DB_NAME'] %>
  user: <%= ENV['RDS_DB_USERNAME'] %>
  password: <%= ENV['RDS_DB_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>


development: &development
  <<: *default
  adapter: postgresql
  <<: *development_env

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  adapter: postgresql
  <<: *test_env

staging: &staging
  <<: *default
  adapter: postgresql
  <<: *elastic_beanstalk_leader_env

production:
  <<: *default
  adapter: postgresql
  <<: *elastic_beanstalk_leader_env
